spring:
  application:
    name: realword
  datasource:
    url: jdbc:h2:~/realworld
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
jwt:
  secret: realword
  expiration: 3600000
  token-prefix: "Bearer "
  header: "Authorization"