name: PR 검증 CI

on:
  pull_request:
    # PR의 대상(target) 브랜치가 main인 경우에 실행합니다.
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # PR에 올라온 브랜치를 체크아웃합니다.
      - name: Checkout PR 브랜치
        uses: actions/checkout@v4

      # JDK 21을 설치합니다.
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Gradle 설정 액션 (캐시 등 최적화를 위해)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # Gradle Wrapper를 이용해 빌드 실행
      - name: Build with Gradle Wrapper
        run: ./gradlew build
